[GLOBAL]
pants_version = "2.15.0"

backend_packages = [
    "pants.backend.python",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.flake8",
    "pants.backend.python.lint.isort",
    "pants.backend.build_files.fmt.black",
    "pants.backend.python.typecheck.mypy",
]

[python]
interpreter_constraints = ["==3.9.*"]
enable_resolves = true
resolves = { python-default = "lockfiles/python.lock" }
tailor_requirements_targets = false
tailor_ignore_empty_init_files = false

[python-bootstrap]
search_path = ["<PATH>", "<PYENV>"]

[anonymous-telemetry]
enabled = true
repo_id = "a291b714-4b91-4b0a-8450-55df904d0e6e"

[source]
root_patterns = ["/"]

[black]
config="pyproject.toml"
lockfile = "lockfiles/black.lock"
export = false

[isort]
config=["pyproject.toml"]
lockfile = "lockfiles/isort.lock"
export = false